spring:
    application:
        name: exchange
management:
    endpoint:
        health:
            probes:
                enabled: true
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info
